<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Api_get_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    function get_data_barang()
    {
        $this->db->select('b.id,b.cabang_id,b.produk_id,b.nama,b.detail,b.harga,b.foto,b.harga_beli,b.kimochi_wallet');
        $this->db->select('p.kategori_id');
        // $this->db->select('');
        $this->db->from('barang AS b');
        // $this->db->order_by('close', 'DESC');
        $this->db->join('produk AS p', 'p.id = b.produk_id');
        // $this->db->join('pegawai', 'pegawai.id = responsible.pegawai_id');
        // $this->db->join('cabang', 'cabang.id = responsible.cabang_id');
        $this->db->where('b.status !=','delete' );
        $query =  $this->db->get();
        return $query->result_array();
    }
    function get_total_customer($where)
    {
        $this->db->select('count(DISTINCT (customer_id)) AS c');
        $this->db->where($where);
        return $this->db->get('taking_order')->row();
    }
    function get_total_antrian($where)
    {
        $this->db->select('count(DISTINCT (tr_id)) AS c');
        $this->db->where($where);
        return $this->db->get('taking_order')->row();
    }
}
