<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Produk extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }
    //THE MASTER OF THE MASTER
    /*
     * Get allowed_payment by id
     */
    public function get_def_all($tabel)
    {
        $data =  array();
        $this->db->select('J.nama,J.id');
        $this->db->select('K.nama,K.id');
        $this->db->from('produk AS P');
        $this->db->join('jenis AS J', 'J.id = P.jenis_id');
        $this->db->join('kategori AS K', 'K.id = P.kategori_id');
        $data['def'] =  $this->db->get()->result();
        return $data;
    }
}
